export {
  diffClientProjections,
  projectGameState,
} from './client-projection.js';
export type {
  ExecuteGameCommandRequest,
  GameActionRequest,
  GameCommandResult,
  GameCommandWire,
  GameDelta,
  GameErrorCode,
  GameErrorResponse,
  GameEventWire,
  GameStateResponse,
  NewGameRequest,
  NewGameResponse,
  VisibleGameState,
} from './schemas.js';
export {
  ActionIdSchema,
  AIBehaviorSchema,
  CharacterTypeSchema,
  DirectionSchema,
  EnemySchema,
  EnemyTypeSchema,
  EnemyVariantSchema,
  EquipmentSchema,
  ExecuteGameCommandRequestSchema,
  FacingDirectionSchema,
  GAMEPLAY_PROTOCOL_HEADER,
  GAMEPLAY_PROTOCOL_VERSION,
  GameActionRequestSchema,
  GameCommandResultSchema,
  GameCommandSchema,
  GameDeltaSchema,
  GameErrorCodeSchema,
  GameErrorResponseSchema,
  GameEventSchema,
  GameplayProtocolVersionSchema,
  GameStateResponseSchema,
  GameStatusSchema,
  ItemSchema,
  NewGameRequestSchema,
  NewGameResponseSchema,
  PlayerEquipmentSchema,
  PlayerSchema,
  TileSchema,
  VisibleGameStateSchema,
} from './schemas.js';
